version: '3.5'

services:

  noise-sink:
    image: local/noise-sink:latest
    container_name: noise-sink
    restart: always
    command: ["sh", "-c", "go run main.go"]
    ports:
      - "8000:8000"
    networks:
      - cloudnet

  noise-flow:
    image: local/noise-flow:latest
    container_name: noise-flow
    restart: always
    command: ["sh", "-c", "yomo run app.go -p 4242"]
    networks:
      - cloudnet

  noise-zipper:
    image: local/noise-zipper:latest
    container_name: noise-zipper
    restart: always
    command: ["sh", "-c", "yomo wf run workflow.yaml"]
    ports:
      - "9999:9999/udp"
    links:
      - noise-flow
      - noise-sink
    depends_on:
      - noise-flow
      - noise-sink
    networks:
      - cloudnet


networks:
  cloudnet:
    driver: bridge
